spring:
  main:
    banner-mode: off


  datasource:
    url: jdbc:mysql://localhost:3306/shop
    name: root
    password: 7203312
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


