spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 7203312

  liquibase:
    change-log: classpath:db\changelog\changes\changelog-master.xml

